# pyinstaller --console --one-file .\sourcehold\__main__.py 


name: Python pyinstaller

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_pyinstaller:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [windows-latest]
        platform: [x86]
        python-version: ['3.13']
        python-platform: [x86]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-platform }}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.4.1
        with:
          arch: ${{ matrix.python-platform }}
        if: matrix.os == 'windows-latest'
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools Cython
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Install GitHub CLI
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
        shell: bash
      - name: Install GitHub CLI (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install gh -y
        shell: pwsh
      - name: Run pyinstaller
        shell: bash
        run: |
          python -m pip install pyinstaller
          pyinstaller --console --onefile ./sourcehold/__main__.py --name sourcehold
      - name: Ensure special latest release exists
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Set continue on error to true
          set +e
          if [[ "$(gh release view latest 2>&1)" == "release not found" ]]; then
            set -e
            gh release create latest --latest
          fi
      - name: Upload pyinstaller to special latest release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest dist/sourcehold* --clobber
      - name: Ensure release exists
        if: github.ref_type == 'tag'
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Set continue on error to true
          set +e
          if [[ "$(gh release view ${{ github.ref_name }} 2>&1)" == "release not found" ]]; then
            set -e
            gh release create ${{ github.ref_name }} --latest
          fi
      - name: Upload pyinstaller to release
        if: github.ref_type == 'tag'
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} dist/sourcehold*