name: Build AIV to AIVJSON GUI (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-gui-converter:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install pyinstaller ttkbootstrap
          pip install -r requirements.txt

      - name: Download wheel dependencies
        run: |
          mkdir dist\deps
          pip download -r requirements.txt -d dist\deps
          pip download ttkbootstrap -d dist\deps

      - name: Build GUI converter .exe with PyInstaller
        run: |
          pyinstaller --onefile --name aiv2json_gui sourcehold/tool/convert/aiv/gui.py

      - name: Upload GUI converter and dependencies as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiv2json_gui-full
          path: |
            dist/aiv2json_gui.exe
            dist/deps/
