name: Отладка AIV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование кода
        uses: actions/checkout@v4
        with:
          ref: ec255bf560684896b4aad3265bca0a4d7b763327

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install .

      - name: Проверка файлов в resources/aiv
        run: |
          ls -l resources/aiv/
          if [ ! -d "resources/aiv" ] || [ -z "$(ls -A resources/aiv/*.aiv)" ]; then
            echo "Ошибка: папка resources/aiv пуста или не содержит .aiv файлов"
            exit 1
          fi

      - name: Запуск тестов
        env:
          BASEPATH: ./resources/aiv
        run: |
          python -m unittest test_aiv.py -v || true

      - name: Загрузка результатов
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: |
            output/
            *.log
