name: Тестирование и загрузка AIV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Необходимо для загрузки активов релиза

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Клонирование кода
        uses: actions/checkout@v4

      # Настройка Python
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Установка зависимостей
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install .  # Установка sourcehold-maps

      # Установка GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
        shell: bash

      # Проверка наличия .aiv файлов
      - name: Проверка файлов в resources/aiv
        run: |
          ls -l resources/aiv/
          if [ ! -d "resources/aiv" ] || [ -z "$(ls -A resources/aiv/*.aiv)" ]; then
            echo "Ошибка: папка resources/aiv пуста или не содержит .aiv файлов"
            exit 1
          fi

      # Запуск тестов
      - name: Запуск юнит-тестов
        env:
          BASEPATH: ./resources/aiv
        run: |
          python -m unittest tests/aiv/test_aiv_to_json.py -v || true

      # Создание файлов для загрузки
      - name: Создание файлов в dist
        run: |
          mkdir -p dist
          # Пример: копируем .aiv файлы в dist как sourcehold*
          for file in resources/aiv/*.aiv; do
            cp "$file" "dist/sourcehold-$(basename "$file")"
          done
          ls -l dist/

      # Проверка релиза latest
      - name: Создание релиза, если не существует
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest --title "Latest Release" --notes "Автоматический релиз" --draft || true
        if: github.event_name == 'push'

      # Загрузка активов в релиз
      - name: Загрузка активов
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest dist/sourcehold* --clobber
        if: github.event_name == 'push'

      # Загрузка результатов
      - name: Загрузка результатов
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: |
            output/
            dist/
            *.log
