name: Build AIV to AIVJSON Converter (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-converter:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build CLI converter .exe with PyInstaller
        run: |
          pyinstaller --onefile --name aiv2json_converter sourcehold/__main__.py --console

      - name: Build GUI converter .exe with PyInstaller
        run: |
          pyinstaller --onefile --name aiv2json_gui sourcehold/tool/convert/aiv/gui.py

      - name: Upload CLI converter .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiv2json_converter-exe
          path: dist/aiv2json_converter.exe

      - name: Upload GUI converter .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiv2json_gui-exe
          path: dist/aiv2json_gui.exe
